package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

func genMCPCmd() *cobra.Command {
	var (
		specPath string
		outDir   string
		name     string
		baseURL  string
	)

	cmd := &cobra.Command{
		Use:   "mcp",
		Short: "Generate a Model Context Protocol (MCP) server from OpenAPI spec",
		Long: `Generate an MCP (Model Context Protocol) server package from an OpenAPI 3.0/3.1 spec.
The generated server allows Claude Desktop, Cursor, Cline, and LLM Agents to discover
and execute the service's API endpoints via Function Calling.

  myapp openapi -o /tmp/catalog.openapi.yaml
  fxkit gen mcp --spec /tmp/catalog.openapi.yaml --out ./cmd/catalog-mcp --base-url http://127.0.0.1:8080

The generated command supports:
  ./catalog-mcp                     # Stdio transport (default, for Claude Desktop / Cursor)
  ./catalog-mcp --transport http    # HTTP POST JSON-RPC 2.0 transport
`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return generateMCP(mcpGenInput{
				SpecPath: specPath,
				OutDir:   outDir,
				Name:     name,
				BaseURL:  baseURL,
			})
		},
	}

	cmd.Flags().StringVar(&specPath, "spec", "", "OpenAPI YAML/JSON file path (required)")
	cmd.Flags().StringVar(&outDir, "out", "", "output directory path (required)")
	cmd.Flags().StringVar(&name, "name", "", "MCP server name (default: basename of outDir)")
	cmd.Flags().StringVar(&baseURL, "base-url", "http://127.0.0.1:8080", "target backend service base URL")

	_ = cmd.MarkFlagRequired("spec")
	_ = cmd.MarkFlagRequired("out")

	return cmd
}

type mcpGenInput struct {
	SpecPath string
	OutDir   string
	Name     string
	BaseURL  string
}

func generateMCP(in mcpGenInput) error {
	specPath := strings.TrimSpace(in.SpecPath)
	outDir := strings.TrimSpace(in.OutDir)
	baseURL := strings.TrimSpace(in.BaseURL)
	if baseURL == "" {
		baseURL = "http://127.0.0.1:8080"
	}

	if specPath == "" {
		return fmt.Errorf("gen mcp: --spec is required")
	}
	if outDir == "" {
		return fmt.Errorf("gen mcp: --out is required")
	}

	specData, err := os.ReadFile(specPath)
	if err != nil {
		return fmt.Errorf("gen mcp read spec: %w", err)
	}
	if len(strings.TrimSpace(string(specData))) == 0 {
		return fmt.Errorf("gen mcp: spec %s is empty", specPath)
	}

	serverName := strings.TrimSpace(in.Name)
	if serverName == "" {
		serverName = filepath.Base(outDir)
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("gen mcp mkdir: %w", err)
	}

	// 1. 写入 openapi.yaml
	if err := os.WriteFile(filepath.Join(outDir, "openapi.yaml"), specData, 0o644); err != nil {
		return fmt.Errorf("gen mcp write openapi.yaml: %w", err)
	}

	// 2. 写入 main.go
	mainSrc, err := renderMCPMain(serverName, baseURL)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "main.go"), mainSrc, 0o644); err != nil {
		return fmt.Errorf("gen mcp write main.go: %w", err)
	}

	// 3. 写入 claude_desktop_config.json 示例
	desktopConfig := fmt.Sprintf(`{
  "mcpServers": {
    "%s": {
      "command": "go",
      "args": ["run", ".", "--base-url", "%s"]
    }
  }
}
`, serverName, baseURL)
	if err := os.WriteFile(filepath.Join(outDir, "claude_desktop_config.json"), []byte(desktopConfig), 0o644); err != nil {
		return fmt.Errorf("gen mcp write claude_desktop_config.json: %w", err)
	}

	// 4. 写入 README.md
	readmeContent := fmt.Sprintf(`# %s MCP Server

Model Context Protocol (MCP) server generated by `+"`fxkit gen mcp`"+`.

## Quick Start

### 1. Run via Stdio (Claude Desktop / Cursor)
`+"```bash"+`
go run . --base-url %s
`+"```"+`

### 2. Configure with Claude Desktop
Add this to your `+"`claude_desktop_config.json`"+`:
`+"```json"+`
{
  "mcpServers": {
    "%s": {
      "command": "%s",
      "args": ["--base-url", "%s"]
    }
  }
}
`+"```"+`

### 3. Run via HTTP JSON-RPC 2.0
`+"```bash"+`
go run . --transport http --port 9090 --base-url %s
`+"```"+`
`, serverName, baseURL, serverName, filepath.Join("/path/to", serverName), baseURL, baseURL)

	if err := os.WriteFile(filepath.Join(outDir, "README.md"), []byte(readmeContent), 0o644); err != nil {
		return fmt.Errorf("gen mcp write README.md: %w", err)
	}

	return nil
}

func renderMCPMain(name, defaultBaseURL string) ([]byte, error) {
	src := fmt.Sprintf(`package main

import (
	"context"
	_ "embed"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/fitan/fxkit/mcpx"
)

//go:embed openapi.yaml
var openapiSpec []byte

func main() {
	var (
		transport = flag.String("transport", "stdio", "transport mode: stdio or http")
		port      = flag.Int("port", 9090, "port for http transport")
		baseURL   = flag.String("base-url", "%s", "target backend microservice URL")
	)
	flag.Parse()

	if envURL := os.Getenv("SERVICE_BASE_URL"); envURL != "" {
		*baseURL = envURL
	}

	tools, err := mcpx.ParseOpenAPI(openapiSpec)
	if err != nil {
		log.Fatalf("failed to parse openapi spec: %%v", err)
	}

	srv := mcpx.NewServer(mcpx.ServerConfig{
		Name:    "%s",
		Version: "1.0.0",
		BaseURL: *baseURL,
	}, tools)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	switch *transport {
	case "stdio":
		if err := srv.ServeStdio(ctx, os.Stdin, os.Stdout); err != nil {
			log.Fatalf("stdio server error: %%v", err)
		}
	case "http":
		addr := fmt.Sprintf(":%%d", *port)
		httpServer := &http.Server{
			Addr:    addr,
			Handler: srv.HTTPHandler(),
		}
		go func() {
			<-ctx.Done()
			shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			defer cancel()
			_ = httpServer.Shutdown(shutdownCtx)
		}()
		log.Printf("MCP HTTP server listening on %%s (target backend: %%s)", addr, *baseURL)
		if err := httpServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("http server error: %%v", err)
		}
	default:
		log.Fatalf("unknown transport: %%s (must be stdio or http)", *transport)
	}
}
`, defaultBaseURL, name)

	formatted, err := format.Source([]byte(src))
	if err != nil {
		return []byte(src), fmt.Errorf("gofmt main.go: %w", err)
	}
	return formatted, nil
}
